name: Xcode - Build and Analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node dependencies
        working-directory: .
        run: yarn

      - name: Build ipa for distribution
        run: |
            - xcodebuild clean -project ./ios/InflationCalc.xcodeproj -scheme SchemeName | xcpretty
            - xcodebuild test -project ./ios/InflationCalc.xcodeproj -scheme SchemeName -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.2' | xcpretty -s
     
